- name: Install mariadb repo
  shell: curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash

- name: Install packages that are needed for mariadb
  dnf:
    name:
      - "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages }}"

- name: Enable mariadb so that it starts on reboots
  systemd:
    name: mariadb
    enabled: true

- name: Start mariadb up
  systemd:
    name: mariadb
    state: started
